import type { Metadata } from "next";
import "./globals.css";
import VideoBackground from "@/components/videoBackground";
import { MainWrapper } from "@/wrappers/MainWrapper";

export const metadata: Metadata = {
  title: "Brian Adhitya",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="overflow-y-scroll">
        <MainWrapper>
          <VideoBackground />
          {children}
        </MainWrapper>
      </body>
    </html>
  );
}
